theme: jekyll-theme-cayman 
description: "The fourth international workshop on the role of resources in the age of large language models"
basepath: "resourceful-2026/"


navigation:
  - text: Home
    url: /index.html
  - text: Programme
    url: /schedule.html
  - text: Keynote speakers
    url: /invited_speakers.html
  - text: Important dates
    url: /dates.html
  - text: Submission details
    url: /submission_details.html
  - text: Organisation
    url: /organisation.html
